version: '3.8'

services:
  gc-testing-app-g1gc-k6:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - test-network-k6
    environment:
      - G1GC_PARAMS=-XX:+UseG1GC

  gc-testing-app-zgc-k6:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - test-network-k6
    environment:
      - ZGC_PARAMS=-XX:+UseZGC

networks:
  test-network:
    driver: bridge
    external: true
