version: '3.8'

services:
  gc-testing-app-g1gc-k6:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gc-testing-app-g1gc-k6
    ports:
      - "8085:8080"
    networks:
      - test-network-k6
    environment:
      - G1GC_PARAMS=-XX:+UseG1GC

  gc-testing-app-zgc-k6:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gc-testing-app-zgc-k6
    ports:
      - "8086:8080"
    networks:
      - test-network-k6-2
    environment:
      - ZGC_PARAMS=-XX:+UseZGC

networks:
  test-network-k6-2:
    driver: bridge
  test-network-k6:
    driver: bridge
