name: Comparison of Garbage Collectors

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      IMAGE_NAME: "gc-testing-image"
      APP_PORT: 8080
      G1GC_PARAMS: "-XX:+UseG1GC -XX:+UnlockDiagnosticVMOptions -XX:+PrintGCDetails"
      ZGC_PARAMS: "-XX:+UseZGC -XX:+UnlockDiagnosticVMOptions -XX:+LogGC"

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      # Set up Gradle
      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      # Make Gradlew executable
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Build the JAR file
      - name: Build the JAR file
        run: ./gradlew build

      # Create Docker network
      - name: Create network
        run: docker network create test-network-k6

      #Create docker network
      - name: Create docker network for zgc
        run: docker network create test-network-k6-2

      #create log directory
      - name: Create directory to save logs
        run: mkdir -p ${{ github.workspace }}/logs
          touch ${{ github.workspace }}/logs/g1gc.logs
          chmod 777 ${{ github.workspace }}/logs/g1gc.logs

      # Build and start the G1GC container
      - name: Run G1GC Container
        run: |
          docker compose up -d gc-testing-app-g1gc-k6
          docker ps
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      # Wait for G1GC service to be ready
      - name: Wait for G1GC Application to start
        run: sleep 5

      # Create Results File for G1GC
      - name: Create Results File for G1GC
        run: |
          mkdir -p ${{ github.workspace }}/results
          touch ${{ github.workspace }}/results/g1gc_results.json
          chmod 777 ${{ github.workspace }}/results/g1gc_results.json
      # Run K6 tests for G1GC
      - name: Run K6 Tests (G1GC)
        run: |
          docker run \
          --network test-network-k6 \
          -v ${{ github.workspace }}/k6-scripts:/scripts \
          -v ${{ github.workspace }}/results:/results \
          -w /results \
          grafana/k6:latest run \
          --summary-export=g1gc_results.json \
          /scripts/g1gc_test.js
          
          docker logs gc-testing-app-g1gc-k6
      # Upload G1GC Logs as Artifact
      - name: Upload G1GC Logs Artifact
        uses: actions/upload-artifact@v4
        with:
          name: g1gc_logs
          path: g1gc.log

      # Stop and remove the G1GC container
      - name: Stop and Remove G1GC Container
        run: |
          docker compose down --remove-orphans
          docker rm -f $(docker ps -aq)

      #create log directory
      - name: Create directory to save logs
        run: mkdir -p ${{ github.workspace }}/logs
          touch ${{ github.workspace }}/logs/zgc.logs
          chmod 777 ${{ github.workspace }}/logs/zgc.logs

      # Build and start the ZGC container
      - name: Run ZGC Container
        run: |
          docker compose up -d gc-testing-app-zgc-k6
          docker ps
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      # Wait for ZGC service to be ready
      - name: Wait for ZGC Application to start
        run: sleep 5

      # Create Results File for ZGC
      - name: Create Results File for ZGC
        run: |
          mkdir -p ${{ github.workspace }}/results
          touch ${{ github.workspace }}/results/zgc_results.json
          chmod 777 ${{ github.workspace }}/results/zgc_results.json

      # Run K6 tests for ZGC
      - name: Run K6 Tests (ZGC)
        run: |
          docker run \
          --network test-network-k6-2 \
          -v ${{ github.workspace }}/k6-scripts:/scripts \
          -v ${{ github.workspace }}/results:/results \
          -w /results \
          grafana/k6:latest run \
          --summary-export=zgc_results.json \
          /scripts/zgc_test.js
          
          docker logs gc-testing-app-zgc-k6
      # Upload ZGC Logs as Artifact
      - name: Upload ZGC Logs Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zgc_logs
          path: zgc.log

      # Stop and remove the ZGC container
      - name: Stop and Remove ZGC Container
        run: |
          docker compose down --remove-orphans
      # Publish Test Results
      - name: Publish G1GC Test Results to GitHub Packages
        uses: actions/upload-artifact@v4
        with:
          name: g1gc_results
          path: results/g1gc_results.json

      - name: Publish ZGC Test Results to GitHub Packages
        uses: actions/upload-artifact@v4
        with:
          name: zgc_results
          path: results/zgc_results.json